dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.2.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  firebase_storage: ^11.0.1
  video_player: ^2.4.5
  camera: ^0.14.0
  image_picker: ^0.8.7
